# Generated by Django 5.2.3 on 2025-09-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatpaat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
