# Generated by Django 5.2.3 on 2025-09-19 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatpaat_app', '0003_chat_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
    ]
